#!/bin/dash
linebuffer_hack="stdbuf -o0"
default_transformer="$(command -v cat)"

[ "$(id -u)"x = "0"x ] && {
	echo Running as root is dangerous, and therefore disabled in script $(readlink -f $0) >&2;
	exit 1;
};

test -z "$1" || [ "$1"x = "-h"x ] || [ "$1"x = "--help"x ] && {
	cat <<EOF >&2 ;
Usage: $(basename $0) <path to topic> [transformer]
	This script pipes newly written lines in file \$1 to transformer \$2 as line-buffered stdin
	If \$2 is not specified, $default_transformer is used as default. The topic, or 1st argument will be created if it does not exist
	Example: $(basename $0) "topicFile" cat -- This will write every new line written to topicFile to stdout
EOF
	exit 1;
};

topic="$1"
test -e "$topic" || touch "$topic"
test -r "$topic" || {
	echo Topic $topic not readable from $PWD with path $PATH Check path and permissions >&2;
	exit 1;
};

transformer="$2"
test -z "$transformer" && {
	transformer="$default_transformer";
};

test -x "$(command -v $transformer)" || {
	echo Transformer $transformer not executable from $PWD with path $PATH Check path and permissions >&2;
	exit 1;
};

subscriber() {
  echo "$1" | $linebuffer_hack $transformer &
}

tail -n 0 -f "$topic" 2>/dev/null | while read line; do subscriber "$line"; done
